### ISSUE TITLE
Add French language support to DiscordTel

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#11]
We got a *611 call earlier from a French person who couldn't understand the English >wizard, etc etc.
Since you speak French yourself, couldn't you add it?

**Comment by Keanu73** [comment]
#12 French documentation for adding a number with DiscordTel - thanks smartbunny009

**Comment by ry00000** [comment]
tbh this should be closed.

**Comment by Keanu73** [comment]
@ry00000 it's still a valid issue

**Comment by Tempestius** [comment]
closing because austin removed his assignment, >suggest

**Comment by Keanu73** [comment]
what? he probs removed it so he didnt get notifications

this is **still** a valid issue

**Comment by austinhuang0131** [comment]
Discord is still mainly composed of English users, plus the code itself isn't really suitable for translation. Still, 611 should handle foreign language stuff
