### ISSUE TITLE
Discord Developer ToS violation (And privacy issue?)

### ISSUE THREAD

**Issue by cfanoulis** [austinhuang0131/discordtel#114]
In https://github.com/austinhuang0131/discordtel/blob/master/DiscordTel.js , line 227, you (blatantly) log every messgae that starts with your prefix. This can be found violating sections 2.4 and 2.5 of the [Discord Developer Terms of Service](https://discordapp.com/developers/docs/legal#2-license-accounts-and-restrictions), as messages fall under EUD (End User Data).

While the Terms do state that you may keep chat logs **if necessary for the operation of your Applications**, I highly doubt that it is of vital importance that you log **every** message that begins with your prefix

As this is a one-line fix, I'd suggest that you probably fix this :D 

Happy February

**Comment by austinhuang0131** [comment]
will do, please dm next time
