### ISSUE TITLE
Double msg

### ISSUE THREAD

**Issue by Mitchell3514** [austinhuang0131/discordtel#137]
https://github.com/austinhuang0131/discordtel/blob/38f6ec283167e99392e107130f184636b95572ea/Internals/jobs.js#L146

Merge must've gone wrong

**Comment by Rexogamer** [comment]
will pick this off

**Comment by Rexogamer** [comment]
wait, you fixed this, code the issue

**Comment by Mitchell3514** [comment]
No problem, will code the issue now

**Comment by Rexogamer** [comment]
ha ha

**Comment by Mitchell3514** [comment]
Sorry, sir, this issue has been coded already.
