### ISSUE TITLE
Convert broken

### ISSUE THREAD

**Issue by Mitchell3514** [austinhuang0131/discordtel#138]
Explains itself

**Comment by Mitchell3514** [comment]
https://github.com/austinhuang0131/discordtel/blob/f713a0274a8819b32ccd534e114d1114dc1eec3f/Commands/Public/convert.js#L7

**Comment by Rexogamer** [comment]
This is at least mostly an external issue (Discoin is down)

**Comment by Mitchell3514** [comment]
No it isn't

**Comment by Rexogamer** [comment]
ok but discoin is down anyway so transactions are broken

**Comment by Mitchell3514** [comment]
Also it's been fixed
