### ISSUE TITLE
move to node-fetch

### ISSUE THREAD

**Issue by Rexogamer** [austinhuang0131/discordtel#141]
snekfetch has been deprecated and will very possibly cause issues down the line

**Comment by Mitchell3514** [comment]
Some library is known to not function with the Glitch API.

**Comment by Mitchell3514** [comment]
> yeah there's that weird problem that snekfetch >=4.0.0 can't work with discoin
There's no issue, go ahead

**Comment by austinhuang0131** [comment]
Snekfetch has been removed as of https://github.com/austinhuang0131/discordtel/commit/9b7b028ad7fb5c79ec3d3245fec7188801fcba32

Now we shall discuss if we should use chainfetch or node-fetch

**Comment by SunburntRock89** [comment]
Chainfetch is just easier to use, requiring less code and basically just being an instant swap from snek

**Comment by Rexogamer** [comment]
hi sun! ~~forgot you existed~~ sure, anything that’s still supported is fine by me

**Comment by vladfrangu** [comment]
> Chainfetch is just easier to use, requiring less code and basically just being an instant swap from snek

And just saying, chainfetch is a wrapper around node-fetch (since node-fetch by itself isn't the nicest to work with). So, you're still getting the benefit of a maintained library. I just made a helper wrapper around it 😄

**Comment by SunburntRock89** [comment]
Aren't we already using chainfetch..?

**Comment by SunburntRock89** [comment]
We've already finished this...
