### ISSUE TITLE
Move to djs stable

### ISSUE THREAD

**Issue by Mitchell3514** [austinhuang0131/discordtel#154]
Move to discord.js stable branch

**Comment by Mitchell3514** [comment]
Dependent files:

- Events/message
- 411
- promote
- contacts
- probably more

**Comment by SunburntRock89** [comment]
This just isn't worth it Mitchell, we're so far into the D.js master branch, you'd be surprised how much changes, most of which for the better. Not to mention that Vlad said master is being released soon enough. At this point, moving to D.js stable is just something we'll end up regretting when we have to backpedal and goto v12 when it comes out.

**Comment by Rexogamer** [comment]
Agreed, it’s better to just take the lag until we get it fixed than waste time downgrading to v11 (I’m honestly surprised they’re still adding features to v11)
