### ISSUE TITLE
Custom emoji

### ISSUE THREAD

**Issue by Mitchell3514** [austinhuang0131/discordtel#163]
Cleanse inaccessible custom emojis from messages.

**Comment by Mitchell3514** [comment]
It doesn't seem doable within d.js limits. @austinhuang0131 ?

**Comment by austinhuang0131** [comment]
We can still bootleg it…
Parse each emoji
Get guild emojis
For each emoji, does ID exist in guild emojis?
Yes: show
No: replace with emoji name

**Comment by Mitchell3514** [comment]
That would also remove emojis the bot does have access too

**Comment by Mitchell3514** [comment]
It's also hard to tell which emojis are actually in a message

**Comment by Mitchell3514** [comment]
@SunburntRock89 suggestion on how to implement it?

**Comment by SunburntRock89** [comment]
I don't understand the question

**Comment by Mitchell3514** [comment]
How can we identify emojis sent with nitro in a message?

**Comment by SunburntRock89** [comment]
check if user has nitro and if we can see the emoji

**Comment by SunburntRock89** [comment]
although twitch emojis wont work

**Comment by Mitchell3514** [comment]
But how do we parse emojis in a message...?

**Comment by cfanoulis** [comment]
reeegex

**Comment by SunburntRock89** [comment]
:*:

**Comment by SunburntRock89** [comment]
Not rocket science

**Comment by Mitchell3514** [comment]
Yes regex, cool, we now know an emojis name...

**Comment by SunburntRock89** [comment]
can't bots use global emotes?

**Comment by Mitchell3514** [comment]
Actually regex and return guild ID would probably work.
Not sure about global emotes.
This is a long control, not sure if we want to do all this work.

**Comment by cfanoulis** [comment]
well, emojis come in a `<:blobsad:386228996486070272>` form, which kinda means @SunburntRock89's impl doesn't work... but if we had an emoji that could return the ID... 

gib sec, gotta search me archives

**Comment by cfanoulis** [comment]
gottem https://regex101.com/r/lEb1Kz/1/

**Comment by Mitchell3514** [comment]
So this enables Austin's idea.
To check for all emojis we'd have to cache all guild emoji IDs I guess, too much work.

**Comment by cfanoulis** [comment]
not really
its a loop, and an API request

**Comment by Mitchell3514** [comment]
I mean to properly check for ALL emojis the bot can access.
We'd have to store and update ALL guilds' emoji IDs

**Comment by Mitchell3514** [comment]
Ah apparently there's Client#emojis

**Comment by cfanoulis** [comment]
so pseudocode would be:
```js
const match = regex.exec(message);
for(const match of matches) client.emojis.has(match)```

**Comment by Mitchell3514** [comment]
Regex needs fixing, but yes that's the idea

**Comment by Mitchell3514** [comment]
Issue solved, implementation remains todo
