### ISSUE TITLE
Deassigned/non-existent numbers still in *411 registry

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#22]
Please add a check so if a number is de-assigned, or doesn't exist, that it is removed from the *411 registry.
I've saw countless cases of rdialled numbers which **actually** don't exist..

I'll have to get in a PR I guess..

**Comment by austinhuang0131** [comment]
Currently the `>deassign` command removes the number in both registry and *411 so that means I'll have to remove them manually
