### ISSUE TITLE
Transferring credits from one Discord account to another

### ISSUE THREAD

**Issue by Tempestius** [austinhuang0131/discordtel#26]
**>transfer [# of credits] [@username#$$$$]**
**$$$$ = 4 digit number**

Requested by many people in #suggestions
maybe we should do it lol

**Comment by austinhuang0131** [comment]
Transaction fee? :eyes:

**Comment by Keanu73** [comment]
No way
![no fucking way](https://imgur.com/ZKsNGSx)

**Comment by Tempestius** [comment]
Transaction fee sounds good 
Keanu I have no clue how that happened lol

**Comment by Ali365Dash** [comment]
have each transaction approved by CS+?

**Comment by Keanu73** [comment]
that would be quite slow

**Comment by Ali365Dash** [comment]
better than nothing tbh

**Comment by Ultie0** [comment]
Have 5 alt accounts, keep claiming daily then transfer to main account. Why not? :D

**Comment by Keanu73** [comment]
@Ultie0 yeah, well.. i'll ban you 😡

**Comment by RickRolled7891** [comment]
Anyone seen getting daily credits and transferring to one account from multiple accounts will be blacklisted.

**Comment by marens101** [comment]
I reckon it'd be good for instances where like the mods pool credits to pay or if someone's *just* short and a friend is willing to help out.    

I reckon do it, but do transaction fee and/or like discoin has a limit on how many credits per day can be transferred.

**Comment by LewisTehMinerz** [comment]
Sounds like a good idea, and @RickRolled7891's suggestion is good too.

If this does get implemented, you will be blacklisted from the bot if you coin farm.

**Comment by iiSkyii** [comment]
It seems like a good idea, and a way to keep the CS busy XDD.
We'll sit, watching the log, looking for suspicious behavior, oh wow 5 people with the same name just transferred to the same account. That's suspicious.
>blacklist

**Comment by Tempestius** [comment]
I'm going to go ahead and say this isn't going to happen, issue closing.
