### ISSUE TITLE
Mailbox.json missing

### ISSUE THREAD

**Issue by matematrix** [austinhuang0131/discordtel#34]
Hello there,

in the code mailbox.json is referenced: 
`var mailbox_storage=JSON.parse(fs.readFileSync("./mailbox.json","utf8"));`,
 but there is no mailbox.json in the directory, please add it.

**Comment by Keanu73** [comment]
That's because it's on the VPS itself, not on GitHub.

**Comment by matematrix** [comment]
All other .json files are there, too. So at least you can add it 💯
