### ISSUE TITLE
Renewing issues

### ISSUE THREAD

**Issue by matematrix** [austinhuang0131/discordtel#42]
When you want to renew a number, which has expired in e.g. 2017/8, and you renew it for one month, it won't renew it from the current time on, which would be 2017/10, but it would only add +1 at the month. That means that you need to pay for months of no usage. 

 `fs.writeFileSync("./account.json", JSON.stringify(accounts), "utf8");
			numbers.splice(numbers.indexOf(mynumber), 1);
			mynumber.month += parseInt(message.content);
			if (mynumber.month > 12) {
				mynumber.month -= 12;
				mynumber.year += 1;
			}`

To find in lines 1239 - 1245

**Comment by Keanu73** [comment]
Is that a code snippet you came up with or you pulled from the code?

**Comment by matematrix** [comment]
This is a snippet from the code, which I think shows the problematic code.

**Comment by Ali365Dash** [comment]
may fix this in a PR soon™

**Comment by Keanu73** [comment]
Hum.
