### ISSUE TITLE
CLA addition?

### ISSUE THREAD

**Issue by babdab9** [austinhuang0131/discordtel#51]
why not have a CLA to be signed when people commit so they commit on giving regular updates.

Austin ~~is~~ **may** be a dingus

**Comment by austinhuang0131** [comment]
off to the gulag

**Comment by babdab9** [comment]
Just saying... https://cla-assistant.io

**Comment by babdab9** [comment]
easier than...everything

**Comment by austinhuang0131** [comment]
Using the existing SAP agreement has "SAP" in the name so I guess I still need to write one

**Comment by austinhuang0131** [comment]
https://cla-assistant.io/austinhuang0131/discordtel
