### ISSUE TITLE
I18n discussion megathread

### ISSUE THREAD

**Issue by ghost** [austinhuang0131/discordtel#70]
The messages the bot sends (prredefined, not sent when in a call) should be stored in a seperate file.

Sounds easy, but I do not think it is

**Comment by Nickanda** [comment]
Can be easily done with exporting stuff but I don't see the need?

**Comment by babdab9** [comment]
Maybe future translation 😏

**Comment by Keanu73** [comment]
ehh maybe

**Comment by babdab9** [comment]
A. Indeed the title was a bit mixed up
B. **Why the fucking fuck wasn't I following you**

**Comment by austinhuang0131** [comment]
i18n is a pretty far thing for us

**Comment by babdab9** [comment]
what

**Comment by austinhuang0131** [comment]
https://enwp.org/i18n

**Comment by babdab9** [comment]
*when you open your issue in your browser **twice*** 🤦‍♂️

**Comment by babdab9** [comment]
also your link doesnt hwork

**Comment by austinhuang0131** [comment]
fine https://en.wikipedia.org/wiki/i18n

**Comment by NubbyTM** [comment]
i18n is a project for translations etc. Also, dtel isn't big enough for that yet. If it actually does get that big, then support will be added.

**Comment by babdab9** [comment]
I am not aiming for i18n.

**Comment by Nickanda** [comment]
> Maybe future translation 😏

👀

**Comment by babdab9** [comment]
I am officially a dingus. i18n is future translation

**Comment by SunburntRock89** [comment]
I think this one should be held here for a while, we'll do it when we come to it

**Comment by KingDGrizzle** [comment]
Having files for each language is easy.
Having a way to get them is also easy, and can be implemented in less than 10 minutes (thats 10 minutes in my time btw. Others can take a while)

Buutt... While the idea is nice, how would we store language settings? Per-user? Per-guild? Both? All of these are questions that still need answers :smile:

**Comment by babdab9** [comment]
per-user.

**Comment by Keanu73** [comment]
per-user isn't the best idea, i think per server is better

**Comment by KingDGrizzle** [comment]
That moment when the user deleted their account notlikeblob

**Comment by austinhuang0131** [comment]
User deleted, plus not all popular bots have i18n, so let's close it but allow this to be reopened
