### ISSUE TITLE
Adding guild blacklist?

### ISSUE THREAD

**Issue by Ali365Dash** [austinhuang0131/discordtel#72]
I've already started work on this - just thought I might ask you first if it's all right so it doesn't go to waste.
(progress visible at [my fork](https://github.com/ali365dash/discordtel))

**Comment by Keanu73** [comment]
Guild blacklist is a great idea
this is fine

**Comment by austinhuang0131** [comment]
C'est fait

**Comment by Keanu73** [comment]
Non, pas vraiment..
