### ISSUE TITLE
*611 blacklist

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#73]
Ever since DiscordTel started, if you ever prank called `*611`, you would get blacklisted from the entire bot.
This is by no means fair, as only a call to an insignificant hotline would just prevent you from using the bot entirely. So I suggest instead of blacklisting them from the entire bot, we should only blacklist them from calling `*611`.

We could possibly have an option to restrict *611 calling (in the guild) to the server owner or entire guild.

**Comment by austinhuang0131** [comment]
I mean we should regularly clean up blacklist but setting up a separate blacklist isn't really necessary

Or you can let every single number has a blacklist

**Comment by Keanu73** [comment]
But it's unfair to people

**Comment by NubbyTM** [comment]
they will probably get blacklisted another way anyways.

**Comment by austinhuang0131** [comment]
Striking should be a good alternative
