### ISSUE TITLE
Embed fallbacks

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#75]
Time and time again I've seen servers where DiscordTel doesn't work only because the server owner forgot to enable the `Link Embeds` permission, resulting in a not-so-great experience, e.g. unable to renew number. We need to create embed fallbacks or at least a message to tell them to enable Link Embeds so that they can't miss out.

**Comment by Nickanda** [comment]
Might work on it later if no one else is :p

**Comment by NubbyTM** [comment]
I'll work on it. If dtel joins a server and doesn't have embed fallbacks, maybe send a message to the owner?

**Comment by Keanu73** [comment]
That'd be a good idea.

**Comment by NubbyTM** [comment]
#76  - makes a message to either the default channel or the owner's DMs, depending on availability.
