### ISSUE TITLE
fix json imports and catch fs errors

### ISSUE THREAD

**Issue by NubbyTM** [austinhuang0131/discordtel#79]
Some JSON imports aren't done properly, and are imported like `./json/file.js` when they should be imported like `./../json/file.js` if the command file is inside another folder. To prevent these issues from happening, `process.cwd()` should be used. (example: `fs.readFileSync(process.cwd() + "json/file.js")`) This way, in the future when you guys start copying and pasting, you can do it and put it in folders, etc.

also error checks should be performed, just in case the file is corrupt/at a different location.

**Comment by Nickanda** [comment]
The fs methods read through `process.cd`, so we have to run the code as if we were running from the index file.

**Comment by NubbyTM** [comment]
Oh oops. Okay, I'll take your word for it.
