### ISSUE TITLE
Start typing when a user in the channel is typing..

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#80]
You know in Yggsdrasil when it types for the user? (by that I mean it starts the typing event e.g. "<user> is typing...") We should do that.

**Comment by Ali365Dash** [comment]
Wouldn't that cause a bit of lag from receiving the event from every single channel on every single server whenever somebody types?

**Comment by austinhuang0131** [comment]
The bigger problem is that this feature is unstable and may cause the bot to keep typing sometimes

**Comment by Keanu73** [comment]
Hrm

**Comment by SunburntRock89** [comment]
Happening in the rewrite branch

**Comment by SunburntRock89** [comment]
-- Feature is already there
