### ISSUE TITLE
Store number owner when registering number

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#82]
This means that when their number expires.. you can just send them a friend request and tell them to RENEW THEIR NUMBER :mmLol:

**Comment by SunburntRock89** [comment]
Simple to do but, why is it needed? If the number expires it should just send a message in the channel saying it expired

**Comment by Keanu73** [comment]
I'm talkin about when you dial a number and it's expired and then it says "This number has expired. Please contact the number owner to get it renewed." I'm thinking of literally putting their tag in there, like this: "This number has expired. Please contact Keanu73#2193 to get it renewed."

**Comment by austinhuang0131** [comment]
Just use server owner
