### ISSUE TITLE
Prevent users from acquiring infinite money

### ISSUE THREAD

**Issue by Keanu73** [austinhuang0131/discordtel#87]
This happens every now and then when someone like Tempestius decides to add -.6 credits to someone. Theen the bot sets the user's balance to NaN. Aand then they have infinite money. How can we prevent them from using infinite money at all...?

**Comment by ytMrTNT** [comment]
It got put back :(

**Comment by ytMrTNT** [comment]
Well, find the code for 'adding' credits to a user in the code. Look for anything that could cause it.
If you cannot see the problem, try creating a new command for subtracting credits instead of doing -, because that seems to be causing the problem.

**Comment by austinhuang0131** [comment]
check `isNaN()` before add credits?

also

> someone like Tempestius

**Comment by SunburntRock89** [comment]
yeah

**Comment by SunburntRock89** [comment]
Bug fixed in rewrite branch
