### ISSUE TITLE
Remove "New star added" notification from Discord server

### ISSUE THREAD

**Issue by Ali365Dash** [austinhuang0131/discordtel#92]
Why, you may be asking?

![image](https://user-images.githubusercontent.com/7354090/37687381-4d60e0a4-2c93-11e8-9266-8812c623848d.png)

**Comment by Ali365Dash** [comment]
Never mind, I'm an idiot.
Expect to see a new post on https://0131.fider.io.

**Comment by GlitchMasta47** [comment]
Oh yeah I did that.

So many Discords with the GitHub webhook active. Does it really need the star notifications checked? It's stupid.
