### ISSUE TITLE
Caller ID and Hide Your Number

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/discordtel#96]
I'll finish that myself so this issue is just to remind me of that

also raise renew price when they're done

**Comment by Keanu73** [comment]
3 months later..

**Comment by Mitchell3514** [comment]
5 months later...

**Comment by RickRolled7891** [comment]
7 months later....

**Comment by SunburntRock89** [comment]
Remind for rewrite

**Comment by AudiophilewTophat** [comment]
ah shit, here we go again

**Comment by Mitchell3514** [comment]
Implemented
